//! Rendering the generated context files, planning the change set, and applying
//! it. This is the single code path that `sync`, `status`, and `validate` all
//! consume (spec §4).

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::config::Manifest;
use crate::{Ctx, git};

/// The comment line that marks a file as owned by `zpr-dev` (spec §4.2, §4.3).
const GENERATED_MARKER: &str = "<!-- Generated by zpr-dev. Do not edit manually. -->";

/// Name of the shared context file in the context checkout (spec §4.1).
pub(crate) const SHARED_CONTEXT_FILE: &str = "AGENTS.md";

/// Name of the generated Claude Code pointer file (spec §1.4.2).
const CLAUDE_POINTER_FILE: &str = "CLAUDE.md";

/// Shown in the `Source:` header when the context checkout's `HEAD` cannot be
/// read — `validate` reports the underlying problem (§7), so rendering does not
/// need to fail here.
const UNKNOWN_SHA: &str = "unknown";

/// What has to happen to a generated file, or to a repository as a whole
/// (spec §4.6).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    /// Generated file absent.
    Create,
    /// Generated file present but differs from the rendered content.
    Update,
    /// Byte-identical; never rewritten, so `sync` does not churn mtimes.
    Unchanged,
    /// Generated file present but **not** carrying [`GENERATED_MARKER`]: it is a
    /// hand-written file that happens to share the name, so `zpr-dev` did not
    /// write it and must not overwrite it. Overwriting one silently destroys a
    /// repository's own conventions — a repository that maintains its own
    /// `AGENTS.md` should rename it to `AGENTS.repo.md`, which generation
    /// includes rather than replaces.
    Foreign,
    /// The checkout directory does not exist.
    RepoMissing,
}

/// One generated file, fully rendered, with what applying it would do.
#[derive(Debug)]
pub struct PlannedFile {
    pub path: PathBuf,
    pub content: String,
    pub action: Action,
}

/// The generated-file change set for one repository. `action` is the worst-of
/// its files: `Foreign` if either is not ours, else `Create` if either is
/// absent, else `Update` if either differs, else `Unchanged`.
#[derive(Debug)]
pub struct RepoPlan {
    pub name: String,
    pub action: Action,
    pub files: Vec<PlannedFile>,
}

/// What [`apply`] did, counted in files.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct ApplySummary {
    pub created: usize,
    pub updated: usize,
    pub unchanged: usize,
    /// Files left alone because they are not `zpr-dev`'s to write.
    pub skipped_foreign: usize,
}

/// Builds the change set for every repository in the manifest. Reads only; the
/// caller decides whether to apply it.
pub fn plan(ctx: &Ctx, manifest: &Manifest) -> Result<Vec<RepoPlan>> {
    let shared_path = ctx.context.join(SHARED_CONTEXT_FILE);
    let shared = std::fs::read_to_string(&shared_path)
        .with_context(|| format!("cannot read shared context {}", shared_path.display()))?;

    // The header and the rewritten references both need absolute paths, and the
    // context path may well have arrived as `--context .`.
    let context_dir = absolute(&ctx.context);
    let docs_dir = context_dir.join(&manifest.documentation.root);
    let rewrites = context_rewrites(&context_dir)?;
    let shared_body = rewrite_doc_references(&shared, &rewrites);

    let sha = git::head_short(&ctx.context).unwrap_or_else(|_| UNKNOWN_SHA.to_string());

    let mut plans = Vec::with_capacity(manifest.repositories.len());
    for repo in &manifest.repositories {
        let dir = ctx.workspace.join(&repo.name);
        if !dir.is_dir() {
            plans.push(RepoPlan {
                name: repo.name.clone(),
                action: Action::RepoMissing,
                files: Vec::new(),
            });
            continue;
        }

        // Absent is the normal case, so an unreadable local file is treated the
        // same as a missing one: the section is simply omitted.
        let local = std::fs::read_to_string(dir.join(&repo.context.local)).ok();
        let files = vec![
            planned_file(
                dir.join(&repo.context.generated),
                render_agents(&shared_body, local.as_deref(), &sha, &docs_dir),
            )?,
            planned_file(dir.join(CLAUDE_POINTER_FILE), render_claude())?,
        ];

        plans.push(RepoPlan {
            name: repo.name.clone(),
            action: worst_action(&files),
            files,
        });
    }
    Ok(plans)
}

/// Writes every file whose content differs, and nothing else. Under
/// `ctx.dry_run` it prints what it would have written and writes nothing
/// (spec §5.1).
///
/// A file that does not carry [`GENERATED_MARKER`] is never written, even
/// though its content differs: see [`Action::Foreign`]. The warning is printed
/// regardless of `ctx.verbose`, because silently skipping a file the caller
/// asked to regenerate is exactly the kind of surprise this guard exists to
/// prevent.
pub fn apply(ctx: &Ctx, plans: &[RepoPlan]) -> Result<ApplySummary> {
    let mut summary = ApplySummary::default();
    for plan in plans {
        for file in &plan.files {
            match file.action {
                Action::Create => summary.created += 1,
                Action::Update => summary.updated += 1,
                Action::Foreign => {
                    summary.skipped_foreign += 1;
                    if !ctx.quiet {
                        println!(
                            "refusing to overwrite {}: not generated by zpr-dev \
                             (rename it to AGENTS.repo.md to have it included instead)",
                            file.path.display()
                        );
                    }
                    continue;
                }
                Action::Unchanged | Action::RepoMissing => {
                    summary.unchanged += 1;
                    continue;
                }
            }
            let verb = if file.action == Action::Create {
                "create"
            } else {
                "update"
            };
            if ctx.dry_run {
                if !ctx.quiet {
                    println!("would {verb} {}", file.path.display());
                }
                continue;
            }
            std::fs::write(&file.path, &file.content)
                .with_context(|| format!("cannot write {}", file.path.display()))?;
            if ctx.verbose && !ctx.quiet {
                println!("{verb}d {}", file.path.display());
            }
        }
    }
    Ok(summary)
}

/// Renders the generated `AGENTS.md` (spec §4.2). The repository-specific
/// heading is omitted entirely when there is no local context file, rather than
/// emitted empty.
fn render_agents(shared_body: &str, local: Option<&str>, sha: &str, docs_dir: &Path) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str(&format!("<!-- Source: zpr-dev-context @ {sha} -->\n"));
    out.push_str(&format!("<!-- Shared docs: {} -->\n", docs_dir.display()));
    out.push_str("\n# Shared ZPR Development Context\n\n");
    out.push_str(shared_body.trim());
    out.push('\n');
    if let Some(local) = local {
        out.push_str("\n# Repository-Specific Context\n\n");
        out.push_str(local.trim());
        out.push('\n');
    }
    out
}

/// Renders the generated `CLAUDE.md` pointer (spec §4.3). One source of truth,
/// both agents find it.
fn render_claude() -> String {
    format!(
        "{GENERATED_MARKER}\nSee [AGENTS.md](./{SHARED_CONTEXT_FILE}) for shared ZPR development context.\n"
    )
}

/// Pairs each top-level directory of the context checkout with its absolute
/// path, keyed by the directory reference used in the shared context
/// (`docs/`, `skills/`). Longest key first, so [`rewrite_doc_references`]
/// prefers the longer match.
///
/// The trailing slash is part of the key on purpose: keyed on `docs` alone,
/// the English word "docs" in prose would be rewritten to a path. Keying on
/// the directory rather than on each document also covers `docs/`, `skills/`,
/// and every path beneath them with one entry apiece.
fn context_rewrites(context_dir: &Path) -> Result<Vec<(String, String)>> {
    let mut rewrites = Vec::new();
    let entries = match std::fs::read_dir(context_dir) {
        Ok(entries) => entries,
        // A missing context directory yields zero rewrites rather than an
        // error; `plan` has already failed to read the shared context by then.
        Err(_) => return Ok(rewrites),
    };
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().to_string();
        // `.git`, `.claude`: never referenced, and rewriting them would be
        // surprising.
        if name.starts_with('.') || !entry.path().is_dir() {
            continue;
        }
        rewrites.push((
            format!("{name}/"),
            format!("{}/", entry.path().to_string_lossy()),
        ));
    }
    rewrites.sort_by_key(|(relative, _)| std::cmp::Reverse(relative.len()));
    Ok(rewrites)
}

/// Replaces each context-relative directory reference with its absolute path
/// (spec §4.4), which carries every path beneath it with it. Literal
/// replacement driven by the directory listing, so a reference under a
/// directory that does not exist in the context checkout is left untouched.
///
/// A single left-to-right scan, rather than a `replace` per rewrite: replacing
/// `docs/A.md.old` first and then `docs/A.md` would otherwise rewrite the
/// substring inside the path it had just produced.
fn rewrite_doc_references(body: &str, rewrites: &[(String, String)]) -> String {
    // ponytail: O(body * rewrites) scan; build a prefix trie if the context
    // checkout ever grows enough top-level directories to show up in a profile.
    let mut out = String::with_capacity(body.len());
    let mut rest = body;
    'scan: while !rest.is_empty() {
        for (relative, absolute) in rewrites {
            if let Some(tail) = rest.strip_prefix(relative.as_str()) {
                out.push_str(absolute);
                rest = tail;
                continue 'scan;
            }
        }
        let next = rest.chars().next().expect("rest is non-empty");
        out.push(next);
        rest = &rest[next.len_utf8()..];
    }
    out
}

/// Renders one file's plan by comparing it against what is on disk, byte for
/// byte (spec §4.5).
///
/// The marker check runs only on a file that differs: an identical file is ours
/// by definition, since everything we render starts with the marker.
fn planned_file(path: PathBuf, content: String) -> Result<PlannedFile> {
    let action = match std::fs::read_to_string(&path) {
        Ok(existing) if existing == content => Action::Unchanged,
        Ok(existing) if !existing.starts_with(GENERATED_MARKER) => Action::Foreign,
        Ok(_) => Action::Update,
        Err(_) => Action::Create,
    };
    Ok(PlannedFile {
        path,
        content,
        action,
    })
}

/// The repository-level action: `Foreign` beats `Create` beats `Update` beats
/// `Unchanged`. `Foreign` leads because it is the only one a human has to
/// resolve by hand.
fn worst_action(files: &[PlannedFile]) -> Action {
    if files.iter().any(|f| f.action == Action::Foreign) {
        Action::Foreign
    } else if files.iter().any(|f| f.action == Action::Create) {
        Action::Create
    } else if files.iter().any(|f| f.action == Action::Update) {
        Action::Update
    } else {
        Action::Unchanged
    }
}

/// Absolute form of `path` without requiring it to exist.
pub(crate) fn absolute(path: &Path) -> PathBuf {
    std::path::absolute(path).unwrap_or_else(|_| path.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config;

    /// A context checkout plus a workspace, both under one temporary directory.
    struct Fixture {
        _tmp: tempfile::TempDir,
        ctx: Ctx,
    }

    impl Fixture {
        /// Builds a context checkout with a committed `AGENTS.md` referencing
        /// `docs/EXAMPLE.md`, and a workspace holding `zpr-core`.
        fn new(shared_body: &str) -> Self {
            let tmp = tempfile::tempdir().unwrap();
            let context = tmp.path().join("zpr-dev-context");
            let workspace = tmp.path().join("workspace");
            std::fs::create_dir_all(context.join("docs")).unwrap();
            std::fs::create_dir_all(workspace.join("zpr-core")).unwrap();
            std::fs::write(context.join(SHARED_CONTEXT_FILE), shared_body).unwrap();
            std::fs::write(context.join("docs/EXAMPLE.md"), "example\n").unwrap();

            // A real commit so the rendered header carries a real short SHA.
            git::git(&context, &["init", "-b", "main"]).unwrap();
            git::git(&context, &["config", "user.name", "zpr-dev tests"]).unwrap();
            git::git(&context, &["config", "user.email", "tests@example.invalid"]).unwrap();
            git::git(&context, &["config", "commit.gpgsign", "false"]).unwrap();
            git::git(&context, &["add", "-A"]).unwrap();
            git::git(&context, &["commit", "-m", "seed"]).unwrap();

            Fixture {
                _tmp: tmp,
                ctx: Ctx {
                    workspace,
                    context,
                    dry_run: false,
                    verbose: false,
                    quiet: true,
                },
            }
        }

        /// The one-repository manifest matching the fixture layout.
        fn manifest(&self) -> Manifest {
            config::parse(
                "
version: 1
repositories:
  - name: zpr-core
    url: file:///dev/null
",
            )
            .unwrap()
        }

        /// The plan for `zpr-core`.
        fn repo_plan(&self) -> RepoPlan {
            plan(&self.ctx, &self.manifest())
                .unwrap()
                .pop()
                .expect("one repository")
        }

        /// The rendered `AGENTS.md` body for `zpr-core`.
        fn rendered_agents(&self) -> String {
            self.repo_plan().files.remove(0).content
        }
    }

    /// Rewrites for a context checkout containing `docs/` plus `skills/`, with
    /// `docs/` populated from `names`.
    fn rewrites_for(names: &[&str]) -> (tempfile::TempDir, Vec<(String, String)>) {
        let tmp = tempfile::tempdir().unwrap();
        let docs = tmp.path().join("docs");
        std::fs::create_dir_all(tmp.path().join("skills")).unwrap();
        std::fs::create_dir_all(&docs).unwrap();
        for name in names {
            let path = docs.join(name);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, "body\n").unwrap();
        }
        let rewrites = context_rewrites(tmp.path()).unwrap();
        (tmp, rewrites)
    }

    #[test]
    fn rewrites_doc_reference_to_absolute_path() {
        let (tmp, rewrites) = rewrites_for(&["EXAMPLE.md"]);
        let expected = tmp.path().join("docs/EXAMPLE.md");
        let out = rewrite_doc_references("see docs/EXAMPLE.md for detail", &rewrites);
        assert_eq!(out, format!("see {} for detail", expected.display()));
    }

    #[test]
    fn rewrites_directory_reference_to_absolute_path() {
        let (tmp, rewrites) = rewrites_for(&["EXAMPLE.md"]);
        let out = rewrite_doc_references("`docs/` and `skills/`", &rewrites);
        assert_eq!(
            out,
            format!(
                "`{}/` and `{}/`",
                tmp.path().join("docs").display(),
                tmp.path().join("skills").display()
            )
        );
    }

    /// The trailing slash is what distinguishes a directory reference from the
    /// same word in prose.
    #[test]
    fn leaves_bare_directory_word_untouched() {
        let (_tmp, rewrites) = rewrites_for(&["EXAMPLE.md"]);
        let out = rewrite_doc_references("the docs describe skills in detail", &rewrites);
        assert_eq!(out, "the docs describe skills in detail");
    }

    #[test]
    fn leaves_reference_under_unknown_directory_untouched() {
        let (_tmp, rewrites) = rewrites_for(&["EXAMPLE.md"]);
        let out = rewrite_doc_references("see notes/GONE.md", &rewrites);
        assert_eq!(out, "see notes/GONE.md");
    }

    #[test]
    fn rewrites_reference_in_nested_docs_subdirectory() {
        let (tmp, rewrites) = rewrites_for(&["arch/DESIGN.md"]);
        let out = rewrite_doc_references("docs/arch/DESIGN.md", &rewrites);
        assert_eq!(
            out,
            tmp.path().join("docs/arch/DESIGN.md").display().to_string()
        );
    }

    #[test]
    fn skips_dot_directories() {
        let (_tmp, rewrites) = rewrites_for(&["EXAMPLE.md"]);
        assert!(
            rewrites
                .iter()
                .all(|(relative, _)| !relative.starts_with('.'))
        );
    }

    #[test]
    fn header_carries_short_sha_and_absolute_docs_dir() {
        let fixture = Fixture::new("shared body\n");
        let sha = git::head_short(&fixture.ctx.context).unwrap();
        let docs = absolute(&fixture.ctx.context).join("docs");
        let rendered = fixture.rendered_agents();
        assert!(rendered.starts_with(GENERATED_MARKER), "{rendered}");
        assert!(
            rendered.contains(&format!("<!-- Source: zpr-dev-context @ {sha} -->")),
            "{rendered}"
        );
        assert!(
            rendered.contains(&format!("<!-- Shared docs: {} -->", docs.display())),
            "{rendered}"
        );
        assert!(docs.is_absolute());
    }

    #[test]
    fn omits_repo_section_when_agents_repo_md_absent() {
        let fixture = Fixture::new("shared body\n");
        let rendered = fixture.rendered_agents();
        assert!(rendered.contains("# Shared ZPR Development Context"));
        assert!(!rendered.contains("# Repository-Specific Context"));
        assert!(rendered.ends_with("shared body\n"), "{rendered}");
    }

    #[test]
    fn includes_repo_section_when_agents_repo_md_present() {
        let fixture = Fixture::new("shared body\n");
        std::fs::write(
            fixture.ctx.workspace.join("zpr-core/AGENTS.repo.md"),
            "core specifics\n",
        )
        .unwrap();
        let rendered = fixture.rendered_agents();
        assert!(rendered.contains("# Repository-Specific Context"));
        assert!(rendered.ends_with("core specifics\n"), "{rendered}");
    }

    #[test]
    fn claude_pointer_body_is_exact() {
        assert_eq!(
            render_claude(),
            "<!-- Generated by zpr-dev. Do not edit manually. -->\n\
             See [AGENTS.md](./AGENTS.md) for shared ZPR development context.\n"
        );
    }

    #[test]
    fn plan_reports_repo_missing_for_absent_directory() {
        let fixture = Fixture::new("shared body\n");
        std::fs::remove_dir_all(fixture.ctx.workspace.join("zpr-core")).unwrap();
        let repo_plan = fixture.repo_plan();
        assert_eq!(repo_plan.action, Action::RepoMissing);
        assert!(repo_plan.files.is_empty());
    }

    #[test]
    fn plan_reports_unchanged_for_byte_identical_file() {
        let fixture = Fixture::new("shared body referencing docs/EXAMPLE.md\n");
        let first = fixture.repo_plan();
        assert_eq!(first.action, Action::Create);

        let summary = apply(&fixture.ctx, &[first]).unwrap();
        assert_eq!(
            summary,
            ApplySummary {
                created: 2,
                ..Default::default()
            }
        );

        let second = fixture.repo_plan();
        assert_eq!(second.action, Action::Unchanged);
        assert!(second.files.iter().all(|f| f.action == Action::Unchanged));
    }

    /// The regression this guard exists for: `zpr-visaservice` kept its own
    /// hand-written `AGENTS.md`, and generation overwrote it, silently losing
    /// the repository's coding conventions.
    #[test]
    fn apply_refuses_to_overwrite_a_file_it_did_not_generate() {
        let fixture = Fixture::new("shared body\n");
        let hand_written = "# AGENTS.md\n\nOur own conventions.\n";
        let path = fixture.ctx.workspace.join("zpr-core/AGENTS.md");
        std::fs::write(&path, hand_written).unwrap();

        let repo_plan = fixture.repo_plan();
        assert_eq!(repo_plan.action, Action::Foreign);
        assert_eq!(repo_plan.files[0].action, Action::Foreign);

        let summary = apply(&fixture.ctx, &[repo_plan]).unwrap();
        assert_eq!(summary.skipped_foreign, 1);
        assert_eq!(summary.updated, 0);
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            hand_written,
            "the hand-written file must survive apply untouched"
        );
    }

    /// A file we generated on a previous run carries the marker, so a content
    /// change is an ordinary update — the guard must not block normal syncing.
    #[test]
    fn apply_updates_a_file_carrying_the_generated_marker() {
        let fixture = Fixture::new("shared body\n");
        let path = fixture.ctx.workspace.join("zpr-core/AGENTS.md");
        std::fs::write(&path, format!("{GENERATED_MARKER}\nstale content\n")).unwrap();

        let repo_plan = fixture.repo_plan();
        assert_eq!(repo_plan.files[0].action, Action::Update);

        let summary = apply(&fixture.ctx, &[repo_plan]).unwrap();
        assert_eq!(summary.skipped_foreign, 0);
        assert_eq!(summary.updated, 1);
        assert!(
            std::fs::read_to_string(&path)
                .unwrap()
                .contains("shared body")
        );
    }

    #[test]
    fn dry_run_apply_writes_nothing() {
        let mut fixture = Fixture::new("shared body\n");
        fixture.ctx.dry_run = true;
        let repo_plan = fixture.repo_plan();
        let generated = repo_plan.files[0].path.clone();
        apply(&fixture.ctx, &[repo_plan]).unwrap();
        assert!(!generated.exists());
    }
}
